export interface PricingItem {
  name: string;
  price: string;
}

export interface PricingCategory {
  id: string;
  title: string;
  icon: string;
  items: PricingItem[];
}

export const PRICING: PricingCategory[] = [
  {
    id: "threading",
    title: "Threading",
    icon: "✦",
    items: [
      { name: "Eyebrows", price: "£4" },
      { name: "Eyebrow Reshape", price: "£5" },
      { name: "Upper Lip", price: "£2.50" },
      { name: "Chin", price: "£3" },
      { name: "Cheeks", price: "£3" },
      { name: "Sides of Face", price: "£4.50" },
      { name: "Neck", price: "£4.50" },
      { name: "Full Face", price: "£8" },
      { name: "Full Face & Neck", price: "£12" },
      { name: "Forehead", price: "£4" },
    ],
  },
  {
    id: "face-wax-tea-tree",
    title: "Face Wax (Tea Tree)",
    icon: "✦",
    items: [
      { name: "Eyebrows", price: "£4" },
      { name: "Upper Lip", price: "£3" },
      { name: "Chin", price: "£4" },
      { name: "Sides of Face", price: "£5" },
      { name: "Neck", price: "£6" },
      { name: "Forehead", price: "£4" },
      { name: "Full Face", price: "£10" },
      { name: "Full Face & Neck", price: "£14" },
    ],
  },
  {
    id: "face-wax-hot",
    title: "Face Wax (Hot Wax)",
    icon: "✦",
    items: [
      { name: "Eyebrows", price: "£5" },
      { name: "Eyebrow Reshape", price: "£6" },
      { name: "Upper Lip", price: "£4" },
      { name: "Chin", price: "£5" },
      { name: "Sides of Face", price: "£7" },
      { name: "Neck", price: "£7" },
      { name: "Forehead", price: "£5" },
      { name: "Top of Nose", price: "£3" },
      { name: "Inside Nose", price: "£6" },
      { name: "Full Face", price: "£15" },
      { name: "Full Face & Neck", price: "£20" },
    ],
  },
  {
    id: "body-waxing",
    title: "Body Waxing",
    icon: "✦",
    items: [
      { name: "Full Arms", price: "£9" },
      { name: "Half Arms", price: "£7" },
      { name: "Full Legs", price: "£11" },
      { name: "Half Legs", price: "£8" },
      { name: "Underarms", price: "£6" },
      { name: "Underarms (Hot Wax)", price: "£8" },
      { name: "Shoulders", price: "£3" },
      { name: "Full Back", price: "£10" },
      { name: "Half Back", price: "£5" },
      { name: "Full Stomach", price: "£7" },
      { name: "Half Stomach", price: "£5" },
      { name: "Full Front", price: "£10" },
      { name: "Buttocks", price: "£7" },
      { name: "Bikini Line", price: "£8" },
      { name: "Brazilian", price: "£27" },
      { name: "Hollywood", price: "£32" },
      { name: "Full Body", price: "£55" },
      { name: "Full Body & Brazilian", price: "£60" },
      { name: "Full Body & Hollywood", price: "£70" },
    ],
  },
  {
    id: "lashes-brows",
    title: "Eyelash & Brows",
    icon: "✦",
    items: [
      { name: "Eyebrow Tint", price: "£8" },
      { name: "Eyelash Tint", price: "£8" },
      { name: "Eyebrow Lamination", price: "£40" },
      { name: "Eyelash Lift", price: "£40" },
      { name: "Lamination Tint & Wax", price: "£55" },
      { name: "Lash Lift & Tint", price: "£48" },
    ],
  },
  {
    id: "nails",
    title: "Nails",
    icon: "✦",
    items: [
      { name: "Normal Polish", price: "£10" },
      { name: "Gel Polish", price: "£18" },
      { name: "Plain Builder Gel", price: "£25" },
      { name: "Builder with Gel Polish", price: "£28" },
      { name: "Builder French", price: "£28" },
      { name: "Builder with Design", price: "£35" },
      { name: "Builder Extensions", price: "From £38" },
      { name: "Removal with New Set", price: "£8" },
      { name: "Removal", price: "£13" },
      { name: "Builder Gel Infill", price: "£22" },
      { name: "Builder Infill + Polish/French", price: "£25" },
      { name: "Builder Infill + Art", price: "From £30" },
    ],
  },
  {
    id: "manicure",
    title: "Manicure",
    icon: "✦",
    items: [
      { name: "Mini Manicure", price: "£15" },
      { name: "Luxury Manicure", price: "£35" },
    ],
  },
  {
    id: "pedicure",
    title: "Pedicure",
    icon: "✦",
    items: [
      { name: "Mini Pedicure", price: "£15" },
      { name: "Luxury Pedicure", price: "£35" },
    ],
  },
  {
    id: "facials",
    title: "Facials",
    icon: "✦",
    items: [
      { name: "Express Facial", price: "£22" },
      { name: "Deep Cleanse", price: "£30" },
      { name: "Gold Facial", price: "£40" },
      { name: "Get The Glow Facial", price: "£55" },
    ],
  },
  {
    id: "massage",
    title: "Massage",
    icon: "✦",
    items: [
      { name: "Indian Head", price: "£30" },
      { name: "Back Neck Shoulder", price: "£45" },
      { name: "Full Body", price: "£65" },
      { name: "Hot Stone", price: "£75" },
    ],
  },
  {
    id: "hair",
    title: "Hair",
    icon: "✦",
    items: [
      { name: "Fringe", price: "£5" },
      { name: "Feathers", price: "£6" },
      { name: "Dry Cut", price: "£15" },
      { name: "Layers", price: "£15" },
      { name: "Trim with Layers", price: "£25" },
      { name: "Wash, Cut & Blowdry", price: "£55" },
      { name: "Wash, Restyle & Blowdry", price: "£55" },
      { name: "Wash & Blowdry", price: "£35" },
      { name: "Hair Straightening", price: "£15" },
      { name: "Hair Curling", price: "£15" },
      { name: "Hair Mask", price: "£10" },
    ],
  },
  {
    id: "colouring",
    title: "Colouring",
    icon: "✦",
    items: [
      { name: "Retouch", price: "£40" },
      { name: "Full Colour", price: "From £55" },
      { name: "Full Highlights", price: "From £150" },
      { name: "Half Highlights", price: "From £95" },
      { name: "Balayage", price: "From £120" },
      { name: "Toner", price: "£35" },
    ],
  },
];

export const SPECIAL_OFFERS = [
  {
    id: "arms-legs-underarms",
    title: "Smooth Skin Bundle",
    description: "Full Arms + Full Legs + Underarms",
    price: "£23",
    originalPrice: "£26",
    saving: "Save £3",
    badge: "Popular",
  },
  {
    id: "hot-wax-package",
    title: "Hot Wax Package",
    description: "Hot Wax full treatment package",
    price: "£26",
    originalPrice: "£31",
    saving: "Save £5",
    badge: "Value",
  },
  {
    id: "brazilian-package",
    title: "Brazilian Package",
    description: "Complete Brazilian waxing package",
    price: "£32",
    originalPrice: "£38",
    saving: "Save £6",
    badge: "Bestseller",
  },
  {
    id: "bikini-package",
    title: "Bikini Package",
    description: "Complete bikini waxing package",
    price: "£48",
    originalPrice: "£56",
    saving: "Save £8",
    badge: "Value",
  },
  {
    id: "hollywood-package",
    title: "Hollywood Package",
    description: "Full Hollywood waxing package",
    price: "£52",
    originalPrice: "£62",
    saving: "Save £10",
    badge: "Premium",
  },
];
